steps:
  - name: "ubuntu"
    id: copy-common
    args: ["cp", "-r", "common", "cloud/"]

  - name: "node:20"
    id: install
    entrypoint: npm
    args: ["install"]
    dir: "cloud"
    waitFor: ["copy-common"]

  - name: "node:20"
    id: build
    entrypoint: npm
    args: ["run", "compile"]
    dir: "cloud"
    waitFor: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy
    args:
      - functions
      - deploy
      - formatter
      - --gen2
      - --runtime=nodejs20
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=formatter
      - --source=cloud
      - --region=us-east5
      - --memory=4Gi
      - --set-env-vars=PRESET_BASE_PATH=gs://us-east5-cca-composer-fc9d45dd-bucket/data
    waitFor: ["build"]

options:
  logging: CLOUD_LOGGING_ONLY
