steps:
  - name: 'alpine'
    args: ['cp', '-r', 'common', 'cloud-fn/']

  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--workspace', 'cloud-fn']

  # Build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', '--workspace', 'cloud-fn', 'build']

  # Deploy the function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - bqExport
      - --region=us-east5
      - --source=cloud-fn
      - --trigger-http
      - --runtime=nodejs20
      - --memory=512Mi

options:
  logging: CLOUD_LOGGING_ONLY