steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'src/cloud-fn'

  # Build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'src/cloud-fn'

  # Deploy the function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - bqExport
      - --region=us-east5
      - --source=flat-file-formatter/src/cloud-fn
      - --trigger-http
      - --runtime=nodejs20
      - --memory=512Mi

options:
  logging: CLOUD_LOGGING_ONLY